/* Строки лендинга на всех его языках. Один файл на весь сайт.
 *
 * Ключ -> текст. В разметке элемент помечается атрибутом data-i18n (меняется
 * textContent) или data-i18n-aria (меняется aria-label); подставляет их
 * landing/i18n.js.
 *
 * Языки: ru, en, uk, kk — те же четыре, что у правовых документов. Если
 * ключа нет в нужном языке, i18n.js берёт en, потом ru, поэтому новый текст
 * можно завести сначала по-русски и перевести следом — страница не опустеет.
 *
 * Русские значения обязаны совпадать с тем, что написано в разметке: без
 * скрипта страница показывает русский, и расхождение будет видно как
 * подмена текста при загрузке. Сторожит tests/unit/landing-i18n.test.js.
 */
window.LANCIBLE_STRINGS = {
  ru: {
    'chrome.status': 'В активной разработке',
    'chrome.blog': 'Блог',
    'chrome.download': 'Скачать',
    'chrome.home': 'Главная',
    'chrome.releases': 'Все версии',
    'chrome.webapp': 'Веб-версия',
    'chrome.tagline': 'Lancible — учёт времени, который не мешает работать',
    'chrome.consent': 'Настройки cookie',
    'chrome.lang_aria': 'Язык сайта',

    'doc.privacy': 'Конфиденциальность',
    'doc.terms': 'Условия использования',
    'doc.cookies': 'Cookie',
    'doc.refund': 'Возвраты',
    'doc.delete-account': 'Удаление аккаунта',
    'doc.legal': 'Реквизиты',
    'legal.eyebrow': 'Правовая информация',
    'legal.nav': 'Документы',
    'legal.switch': 'Язык документа',
    'legal.blank': '[не заполнено]',

    'home.meta_title': 'Lancible — учёт времени',
    'home.meta_description': 'Lancible — таймер, проекты и календарь в одном месте. Скачайте для Windows, macOS, Android или откройте веб-версию.',
    'home.hero_eyebrow': 'Учёт рабочего времени',
    'home.hero_title1': 'Запускай задачи.',
    'home.hero_title2': 'Следи за ',
    'home.hero_title_em': 'временем',
    'home.hero_title3': '.',
    'home.hero_lede': 'Lancible — таймер, проекты и календарь в одном месте. Работает офлайн, синхронизируется в облаке и выглядит одинаково на любой платформе.',
    'home.hero_cta_web': 'Открыть веб-версию',
    'home.hero_cta_download': 'Скачать приложение',
    'home.hero_note': 'Без карты, без регистрации для начала — просто откройте и запустите таймер',
    'home.hero_timer_proj': 'Дизайн лендинга · Lancible',

    'home.platforms_title': 'Выберите платформу',
    'home.platforms_lede': 'Один и тот же учёт времени — на рабочем столе, в браузере и в кармане. Данные синхронизируются между устройствами через ваш аккаунт.',
    'home.platforms_ready': 'Готово',
    'home.win_desc': 'Установщик .exe с автообновлением. Работает на Windows 10 и 11.',
    'home.win_size': '~78 МБ',
    'home.win_cta': 'Скачать .exe',
    'home.mac_desc': 'Universal-сборка .dmg — работает и на Intel, и на Apple Silicon.',
    'home.mac_size': '~174 МБ',
    'home.mac_cta': 'Скачать .dmg',
    'home.android_desc': 'Прямой .apk — разрешите установку из внешних источников при первом запуске.',
    'home.android_size': '~96 МБ',
    'home.android_cta': 'Скачать .apk',
    'home.web_name': 'Веб-версия',
    'home.web_desc': 'Ничего устанавливать не нужно — откройте lancible.vercel.app/app в любом браузере и начните прямо сейчас.',
    'home.web_cta': 'Открыть в браузере',

    'home.status_eyebrow': 'Статус проекта',
    'home.status_title1': 'Lancible ещё строится —',
    'home.status_title2': 'и это открытый процесс',
    'home.status_lede': 'Приложение уже полностью рабочее и им можно пользоваться каждый день, но команда (пока что — один человек и много кофе) продолжает добавлять платформы и возможности каждую неделю.',
    'home.roadmap_shipped_title': 'Windows, macOS, Android, Web',
    'home.roadmap_shipped_sub': 'Таймер, проекты, задачи, календарь и синхронизация — везде одинаково.',
    'home.roadmap_badge_shipped': 'Вышло',
    'home.roadmap_ios_title': 'Нативное приложение для iOS',
    'home.roadmap_ios_sub': 'Сейчас в разработке. Срок назовём, когда сборка будет готова.',
    'home.roadmap_google_title': 'Вход через Google на телефоне',
    'home.roadmap_google_sub': 'На вебе и десктопе уже работает, для Android и iOS донастраивается.',
    'home.roadmap_badge_progress': 'В работе',
    'home.roadmap_stores_title': 'Публикация в App Store и Google Play',
    'home.roadmap_stores_sub': 'Пока приложения раздаются напрямую — магазины появятся следующим шагом.',
    'home.roadmap_badge_planned': 'Дальше',

    'home.features_title': 'Всё нужное для учёта времени',
    'home.features_lede': 'Без лишних настроек и обучающих туров — открыли и начали считать.',
    'home.feature_timer_title': 'Таймер в один клик',
    'home.feature_timer_desc': 'Старт и стоп без лишних экранов — время сразу привязано к задаче и проекту.',
    'home.feature_projects_title': 'Проекты и задачи',
    'home.feature_projects_desc': 'Группируйте работу по проектам, закрепляйте важное, отмечайте готовое.',
    'home.feature_calendar_title': 'Календарь и отчёты',
    'home.feature_calendar_desc': 'День, неделя и месяц — сколько отработано и сколько заработано, по датам.',
    'home.feature_offline_title': 'Работает офлайн',
    'home.feature_offline_desc': 'Локально всё сохраняется сразу, синхронизация с облаком — как только есть сеть.',

    'blog.eyebrow': 'Блог',
    'blog.title': 'Что нового в Lancible',
    'blog.lede': 'Сюда попадает всё заметное: новые платформы, релизы и крупные возможности. Мелкие правки остаются в истории коммитов.',
    'blog.more': 'Все записи →',
    'blog.empty': 'Записей пока нет — скоро здесь появится первое обновление.',
    'blog.meta_title': 'Блог Lancible',
    'blog.filter_all': 'Все',
    'blog.filter_release': 'Релизы',
    'blog.filter_feature': 'Новое',
    'blog.filter_improvement': 'Улучшения',
    'blog.back': '← На главную',
    'blog.empty_filtered': 'В этой категории пока ничего нет.',
    'blog.tag_release': 'Релиз',
    'blog.tag_feature': 'Новое',
    'blog.tag_improvement': 'Улучшение',
  },

  en: {
    'chrome.status': 'In active development',
    'chrome.blog': 'Blog',
    'chrome.download': 'Download',
    'chrome.home': 'Home',
    'chrome.releases': 'All releases',
    'chrome.webapp': 'Web version',
    'chrome.tagline': 'Lancible — time tracking that stays out of your way',
    'chrome.consent': 'Cookie settings',
    'chrome.lang_aria': 'Site language',

    'doc.privacy': 'Privacy',
    'doc.terms': 'Terms of Service',
    'doc.cookies': 'Cookies',
    'doc.refund': 'Refunds',
    'doc.delete-account': 'Delete account',
    'doc.legal': 'Business details',
    'legal.eyebrow': 'Legal',
    'legal.nav': 'Documents',
    'legal.switch': 'Document language',
    'legal.blank': '[not provided yet]',

    'home.meta_title': 'Lancible — time tracking',
    'home.meta_description': 'Lancible — a timer, projects and a calendar in one place. Download it for Windows, macOS or Android, or open the web version.',
    'home.hero_eyebrow': 'Work time tracking',
    'home.hero_title1': 'Start your tasks.',
    'home.hero_title2': 'Track your ',
    'home.hero_title_em': 'time',
    'home.hero_title3': '.',
    'home.hero_lede': 'Lancible is a timer, projects and a calendar in one place. It works offline, syncs through the cloud and looks the same on every platform.',
    'home.hero_cta_web': 'Open the web version',
    'home.hero_cta_download': 'Download the app',
    'home.hero_note': 'No card, no sign-up to get going — just open it and hit the timer',
    'home.hero_timer_proj': 'Landing page design · Lancible',

    'home.platforms_title': 'Pick your platform',
    'home.platforms_lede': 'The same time tracking on your desktop, in the browser and in your pocket. Data syncs between devices through your account.',
    'home.platforms_ready': 'Ready',
    'home.win_desc': 'An .exe installer with auto-updates. Runs on Windows 10 and 11.',
    'home.win_size': '~78 MB',
    'home.win_cta': 'Download .exe',
    'home.mac_desc': 'A universal .dmg — runs on both Intel and Apple Silicon.',
    'home.mac_size': '~174 MB',
    'home.mac_cta': 'Download .dmg',
    'home.android_desc': 'A direct .apk — allow installs from unknown sources on first launch.',
    'home.android_size': '~96 MB',
    'home.android_cta': 'Download .apk',
    'home.web_name': 'Web version',
    'home.web_desc': 'Nothing to install — open lancible.vercel.app/app in any browser and start right away.',
    'home.web_cta': 'Open in browser',

    'home.status_eyebrow': 'Project status',
    'home.status_title1': 'Lancible is still being built —',
    'home.status_title2': 'and the process is out in the open',
    'home.status_lede': 'The app is already fully working and fine for daily use, but the team (one person and a lot of coffee, so far) keeps adding platforms and features every week.',
    'home.roadmap_shipped_title': 'Windows, macOS, Android, Web',
    'home.roadmap_shipped_sub': 'Timer, projects, tasks, calendar and sync — the same everywhere.',
    'home.roadmap_badge_shipped': 'Shipped',
    'home.roadmap_ios_title': 'Native iOS app',
    'home.roadmap_ios_sub': 'In development. We will name a date once the build is ready.',
    'home.roadmap_google_title': 'Google sign-in on mobile',
    'home.roadmap_google_sub': 'Already working on web and desktop; being set up for Android and iOS.',
    'home.roadmap_badge_progress': 'In progress',
    'home.roadmap_stores_title': 'App Store and Google Play releases',
    'home.roadmap_stores_sub': 'For now the apps are handed out directly — the stores are the next step.',
    'home.roadmap_badge_planned': 'Next',

    'home.features_title': 'Everything you need to track time',
    'home.features_lede': 'No setup rituals and no onboarding tours — open it and start counting.',
    'home.feature_timer_title': 'One-click timer',
    'home.feature_timer_desc': 'Start and stop with no extra screens — time is tied to a task and a project right away.',
    'home.feature_projects_title': 'Projects and tasks',
    'home.feature_projects_desc': 'Group work by project, pin what matters, tick off what is done.',
    'home.feature_calendar_title': 'Calendar and reports',
    'home.feature_calendar_desc': 'Day, week and month — hours worked and money earned, by date.',
    'home.feature_offline_title': 'Works offline',
    'home.feature_offline_desc': 'Everything saves locally at once; the cloud catches up as soon as you are online.',

    'blog.eyebrow': 'Blog',
    'blog.title': 'What’s new in Lancible',
    'blog.lede': 'Everything worth noticing lands here: new platforms, releases and major features. Small fixes stay in the commit history.',
    'blog.more': 'All posts →',
    'blog.empty': 'No posts yet — the first update will show up here soon.',
    'blog.meta_title': 'Lancible blog',
    'blog.filter_all': 'All',
    'blog.filter_release': 'Releases',
    'blog.filter_feature': 'New',
    'blog.filter_improvement': 'Improvements',
    'blog.back': '← Back to home',
    'blog.empty_filtered': 'Nothing in this category yet.',
    'blog.tag_release': 'Release',
    'blog.tag_feature': 'New',
    'blog.tag_improvement': 'Improved',
  },

  uk: {
    'chrome.status': 'В активній розробці',
    'chrome.blog': 'Блог',
    'chrome.download': 'Завантажити',
    'chrome.home': 'Головна',
    'chrome.releases': 'Усі версії',
    'chrome.webapp': 'Веб-версія',
    'chrome.tagline': 'Lancible — облік часу, який не заважає працювати',
    'chrome.consent': 'Налаштування cookie',
    'chrome.lang_aria': 'Мова сайту',

    'doc.privacy': 'Конфіденційність',
    'doc.terms': 'Умови використання',
    'doc.cookies': 'Cookie',
    'doc.refund': 'Повернення коштів',
    'doc.delete-account': 'Видалення акаунта',
    'doc.legal': 'Реквізити',
    'legal.eyebrow': 'Правова інформація',
    'legal.nav': 'Документи',
    'legal.switch': 'Мова документа',
    'legal.blank': '[не заповнено]',

    'home.meta_title': 'Lancible — облік часу',
    'home.meta_description': 'Lancible — таймер, проєкти й календар в одному місці. Завантажте для Windows, macOS, Android або відкрийте веб-версію.',
    'home.hero_eyebrow': 'Облік робочого часу',
    'home.hero_title1': 'Запускай задачі.',
    'home.hero_title2': 'Стеж за ',
    'home.hero_title_em': 'часом',
    'home.hero_title3': '.',
    'home.hero_lede': 'Lancible — таймер, проєкти й календар в одному місці. Працює офлайн, синхронізується у хмарі й виглядає однаково на будь-якій платформі.',
    'home.hero_cta_web': 'Відкрити веб-версію',
    'home.hero_cta_download': 'Завантажити застосунок',
    'home.hero_note': 'Без картки, без реєстрації на початок — просто відкрийте й запустіть таймер',
    'home.hero_timer_proj': 'Дизайн лендінгу · Lancible',

    'home.platforms_title': 'Оберіть платформу',
    'home.platforms_lede': 'Той самий облік часу — на комп’ютері, у браузері та в кишені. Дані синхронізуються між пристроями через ваш акаунт.',
    'home.platforms_ready': 'Готово',
    'home.win_desc': 'Інсталятор .exe з автооновленням. Працює на Windows 10 і 11.',
    'home.win_size': '~78 МБ',
    'home.win_cta': 'Завантажити .exe',
    'home.mac_desc': 'Universal-збірка .dmg — працює і на Intel, і на Apple Silicon.',
    'home.mac_size': '~174 МБ',
    'home.mac_cta': 'Завантажити .dmg',
    'home.android_desc': 'Прямий .apk — дозвольте встановлення зі сторонніх джерел під час першого запуску.',
    'home.android_size': '~96 МБ',
    'home.android_cta': 'Завантажити .apk',
    'home.web_name': 'Веб-версія',
    'home.web_desc': 'Нічого встановлювати не потрібно — відкрийте lancible.vercel.app/app у будь-якому браузері й починайте просто зараз.',
    'home.web_cta': 'Відкрити у браузері',

    'home.status_eyebrow': 'Статус проєкту',
    'home.status_title1': 'Lancible ще будується —',
    'home.status_title2': 'і це відкритий процес',
    'home.status_lede': 'Застосунок уже цілком робочий, ним можна користуватися щодня, але команда (поки що — одна людина й багато кави) щотижня додає платформи та можливості.',
    'home.roadmap_shipped_title': 'Windows, macOS, Android, Web',
    'home.roadmap_shipped_sub': 'Таймер, проєкти, задачі, календар і синхронізація — усюди однаково.',
    'home.roadmap_badge_shipped': 'Вийшло',
    'home.roadmap_ios_title': 'Нативний застосунок для iOS',
    'home.roadmap_ios_sub': 'Зараз у розробці. Строк назвемо, коли збірка буде готова.',
    'home.roadmap_google_title': 'Вхід через Google на телефоні',
    'home.roadmap_google_sub': 'У вебі та на комп’ютері вже працює, для Android та iOS налаштовується.',
    'home.roadmap_badge_progress': 'У роботі',
    'home.roadmap_stores_title': 'Публікація в App Store і Google Play',
    'home.roadmap_stores_sub': 'Поки застосунки роздаються напряму — магазини з’являться наступним кроком.',
    'home.roadmap_badge_planned': 'Далі',

    'home.features_title': 'Усе потрібне для обліку часу',
    'home.features_lede': 'Без зайвих налаштувань і навчальних турів — відкрили й почали рахувати.',
    'home.feature_timer_title': 'Таймер в один клік',
    'home.feature_timer_desc': 'Старт і стоп без зайвих екранів — час одразу прив’язаний до задачі та проєкту.',
    'home.feature_projects_title': 'Проєкти та задачі',
    'home.feature_projects_desc': 'Групуйте роботу за проєктами, закріплюйте важливе, позначайте готове.',
    'home.feature_calendar_title': 'Календар і звіти',
    'home.feature_calendar_desc': 'День, тиждень і місяць — скільки відпрацьовано й скільки зароблено, за датами.',
    'home.feature_offline_title': 'Працює офлайн',
    'home.feature_offline_desc': 'Локально все зберігається одразу, синхронізація з хмарою — щойно з’явиться мережа.',

    'blog.eyebrow': 'Блог',
    'blog.title': 'Що нового в Lancible',
    'blog.lede': 'Сюди потрапляє все помітне: нові платформи, релізи та великі можливості. Дрібні правки лишаються в історії комітів.',
    'blog.more': 'Усі записи →',
    'blog.empty': 'Записів поки немає — скоро тут з’явиться перше оновлення.',
    'blog.meta_title': 'Блог Lancible',
    'blog.filter_all': 'Усі',
    'blog.filter_release': 'Релізи',
    'blog.filter_feature': 'Нове',
    'blog.filter_improvement': 'Покращення',
    'blog.back': '← На головну',
    'blog.empty_filtered': 'У цій категорії поки нічого немає.',
    'blog.tag_release': 'Реліз',
    'blog.tag_feature': 'Нове',
    'blog.tag_improvement': 'Покращення',
  },

  kk: {
    'chrome.status': 'Белсенді әзірленуде',
    'chrome.blog': 'Блог',
    'chrome.download': 'Жүктеу',
    'chrome.home': 'Басты бет',
    'chrome.releases': 'Барлық нұсқа',
    'chrome.webapp': 'Веб-нұсқа',
    'chrome.tagline': 'Lancible — жұмысқа кедергі келтірмейтін уақыт есебі',
    'chrome.consent': 'Cookie параметрлері',
    'chrome.lang_aria': 'Сайт тілі',

    'doc.privacy': 'Құпиялылық',
    'doc.terms': 'Пайдалану шарттары',
    'doc.cookies': 'Cookie',
    'doc.refund': 'Қаражатты қайтару',
    'doc.delete-account': 'Аккаунтты жою',
    'doc.legal': 'Деректемелер',
    'legal.eyebrow': 'Құқықтық ақпарат',
    'legal.nav': 'Құжаттар',
    'legal.switch': 'Құжат тілі',
    'legal.blank': '[толтырылмаған]',

    'home.meta_title': 'Lancible — уақыт есебі',
    'home.meta_description': 'Lancible — таймер, жобалар және күнтізбе бір жерде. Windows, macOS, Android үшін жүктеңіз немесе веб-нұсқаны ашыңыз.',
    'home.hero_eyebrow': 'Жұмыс уақытын есепке алу',
    'home.hero_title1': 'Тапсырмаларды бастаңыз.',
    'home.hero_title2': 'Қадағалаңыз: ',
    'home.hero_title_em': 'уақыт',
    'home.hero_title3': '.',
    'home.hero_lede': 'Lancible — таймер, жобалар және күнтізбе бір жерде. Офлайн жұмыс істейді, бұлтпен синхрондалады және кез келген платформада бірдей көрінеді.',
    'home.hero_cta_web': 'Веб-нұсқаны ашу',
    'home.hero_cta_download': 'Қолданбаны жүктеу',
    'home.hero_note': 'Картасыз, бастау үшін тіркелусіз — жай ғана ашып, таймерді қосыңыз',
    'home.hero_timer_proj': 'Лендинг дизайны · Lancible',

    'home.platforms_title': 'Платформаңызды таңдаңыз',
    'home.platforms_lede': 'Дәл сол уақыт есебі — компьютерде, браузерде және қалтаңызда. Деректер аккаунт арқылы құрылғылар арасында синхрондалады.',
    'home.platforms_ready': 'Дайын',
    'home.win_desc': 'Автожаңартуы бар .exe орнатқышы. Windows 10 және 11 жүйесінде жұмыс істейді.',
    'home.win_size': '~78 МБ',
    'home.win_cta': '.exe жүктеу',
    'home.mac_desc': 'Universal .dmg жинағы — Intel-де де, Apple Silicon-да да жұмыс істейді.',
    'home.mac_size': '~174 МБ',
    'home.mac_cta': '.dmg жүктеу',
    'home.android_desc': 'Тікелей .apk — алғашқы іске қосқанда сыртқы көздерден орнатуға рұқсат беріңіз.',
    'home.android_size': '~96 МБ',
    'home.android_cta': '.apk жүктеу',
    'home.web_name': 'Веб-нұсқа',
    'home.web_desc': 'Ештеңе орнатудың қажеті жоқ — кез келген браузерде lancible.vercel.app/app ашып, қазір бастаңыз.',
    'home.web_cta': 'Браузерде ашу',

    'home.status_eyebrow': 'Жоба күйі',
    'home.status_title1': 'Lancible әлі салынып жатыр —',
    'home.status_title2': 'және бұл ашық үдеріс',
    'home.status_lede': 'Қолданба толық жұмыс істейді және оны күн сайын пайдалануға болады, бірақ команда (әзірге — бір адам және көп кофе) апта сайын платформалар мен мүмкіндіктер қосып келеді.',
    'home.roadmap_shipped_title': 'Windows, macOS, Android, Web',
    'home.roadmap_shipped_sub': 'Таймер, жобалар, тапсырмалар, күнтізбе және синхрондау — бәрінде бірдей.',
    'home.roadmap_badge_shipped': 'Шықты',
    'home.roadmap_ios_title': 'iOS үшін нативті қолданба',
    'home.roadmap_ios_sub': 'Қазір әзірленуде. Мерзімді жинақ дайын болғанда айтамыз.',
    'home.roadmap_google_title': 'Телефонда Google арқылы кіру',
    'home.roadmap_google_sub': 'Вебте және компьютерде жұмыс істейді, Android пен iOS үшін бапталуда.',
    'home.roadmap_badge_progress': 'Жұмыста',
    'home.roadmap_stores_title': 'App Store және Google Play-де жариялау',
    'home.roadmap_stores_sub': 'Әзірге қолданбалар тікелей таратылады — дүкендер келесі қадам болады.',
    'home.roadmap_badge_planned': 'Әрі қарай',

    'home.features_title': 'Уақыт есебіне керектің бәрі',
    'home.features_lede': 'Артық баптаусыз және оқыту турларысыз — ашып, санай бастадыңыз.',
    'home.feature_timer_title': 'Бір басқанда таймер',
    'home.feature_timer_desc': 'Артық экрансыз іске қосу және тоқтату — уақыт бірден тапсырма мен жобаға байланады.',
    'home.feature_projects_title': 'Жобалар мен тапсырмалар',
    'home.feature_projects_desc': 'Жұмысты жобаларға бөліңіз, маңыздысын бекітіңіз, дайынын белгілеңіз.',
    'home.feature_calendar_title': 'Күнтізбе және есептер',
    'home.feature_calendar_desc': 'Күн, апта және ай — қанша жұмыс істелді және қанша табылды, күні бойынша.',
    'home.feature_offline_title': 'Офлайн жұмыс істейді',
    'home.feature_offline_desc': 'Жергілікті түрде бәрі бірден сақталады, бұлтпен синхрондау — желі пайда болған бойда.',

    'blog.eyebrow': 'Блог',
    'blog.title': 'Lancible-де не жаңалық',
    'blog.lede': 'Бұл жерге байқалатынның бәрі түседі: жаңа платформалар, релиздер және ірі мүмкіндіктер. Ұсақ түзетулер коммиттер тарихында қалады.',
    'blog.more': 'Барлық жазба →',
    'blog.empty': 'Әзірге жазба жоқ — жақында мұнда алғашқы жаңарту пайда болады.',
    'blog.meta_title': 'Lancible блогы',
    'blog.filter_all': 'Барлығы',
    'blog.filter_release': 'Релиздер',
    'blog.filter_feature': 'Жаңа',
    'blog.filter_improvement': 'Жақсартулар',
    'blog.back': '← Басты бетке',
    'blog.empty_filtered': 'Бұл санатта әзірге ештеңе жоқ.',
    'blog.tag_release': 'Релиз',
    'blog.tag_feature': 'Жаңа',
    'blog.tag_improvement': 'Жақсарту',
  },
};
